server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password:
  application:
    name: User-Center

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    cn.surkaa: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS(XXX)
  file:
    name: log/book-server.log

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局配置逻辑删除的表字段名 也可以在对应字段添加@TableLogic
      logic-delete-value: 1     # 删除的值
      logic-not-delete-value: 0 # 未删除的值
